version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  commands:
    - rm -rf _readthedocs/html
    - mkdir -p _readthedocs/html
    - mv docs/sphinx-docs/build/html/ _readthedocs/html/
